---
name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  commit_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: webiny/action-conventional-commits@v1.1.0

  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color always --check lua/ tests/

  unit_test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        neovim_branch: ["v0.8.3", "v0.9.2", "nightly"]

    steps:
      - uses: actions/checkout@v3

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_branch }}

      - name: Install dependent repos
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter

      - name: Run tests
        run: |
          make test
